<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.10.2" name="blocks_16x16" tilewidth="16" tileheight="16" tilecount="66" columns="11">
 <image source="../graphics/tilesets/blocks_tiles/blocks.png" width="176" height="96"/>
 <tile id="0" type="block"/>
 <tile id="1" type="block"/>
 <tile id="2" type="block"/>
 <tile id="3" type="block"/>
 <tile id="4" type="block"/>
 <tile id="5" type="block"/>
 <tile id="6" type="block"/>
 <tile id="7" type="block"/>
 <tile id="8" type="block"/>
 <tile id="9" type="block"/>
 <tile id="10" type="block"/>
 <tile id="11" type="block"/>
 <tile id="12" type="block"/>
 <tile id="13" type="block"/>
 <tile id="14" type="block"/>
 <tile id="15" type="block"/>
 <tile id="16" type="block"/>
 <tile id="17" type="block"/>
 <tile id="18" type="block"/>
 <tile id="19" type="block"/>
 <tile id="20" type="block"/>
 <tile id="21" type="block"/>
 <tile id="22" type="block"/>
 <tile id="23" type="block"/>
 <tile id="24" type="block"/>
 <tile id="25" type="block"/>
 <tile id="26" type="block"/>
 <tile id="27" type="block"/>
 <tile id="28" type="block"/>
 <tile id="29" type="block"/>
 <tile id="30" type="block"/>
 <tile id="31" type="block"/>
 <tile id="32" type="block"/>
 <tile id="33" type="block"/>
 <tile id="34" type="block"/>
 <tile id="35" type="block"/>
 <tile id="36" type="block"/>
 <tile id="37" type="block"/>
 <tile id="38" type="block"/>
 <tile id="39" type="block"/>
 <tile id="40" type="block"/>
 <tile id="41" type="block"/>
 <tile id="42" type="block"/>
 <tile id="43" type="block"/>
 <tile id="44" type="block"/>
 <tile id="45" type="block"/>
 <tile id="46" type="block"/>
 <tile id="47" type="block"/>
 <tile id="48" type="block"/>
 <tile id="49" type="block"/>
 <tile id="50" type="block"/>
 <tile id="51" type="block"/>
 <tile id="52" type="block"/>
 <tile id="53" type="block"/>
 <tile id="54" type="block"/>
 <tile id="55" type="block"/>
 <tile id="56" type="block"/>
 <tile id="57" type="block"/>
 <tile id="58" type="block"/>
 <tile id="59" type="block"/>
 <tile id="60" type="block"/>
 <tile id="61" type="block"/>
 <tile id="62" type="block"/>
 <tile id="63" type="block"/>
 <tile id="64" type="block"/>
 <tile id="65" type="block"/>
</tileset>
